[package]
name = "tci"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tci"

[worksoace]
members = [
    "crates/*"
]

[dependencies]
